### ISSUE TITLE
Network Visualization on Map

### ISSUE THREAD

**Issue by eayan** [stellasia/neomap#20] opened 2019-10-10 13:42 UTC
I was just wondering if it is possible to create/visualize network or relationship among the nodes via neomap.
best..
Erdal Ayan

**Comment by stellasia** [comment] 2019-10-10 14:07
Hi @eayan , 
This is not possible yet, but I think it is planned in #15, right?

**Comment by stellasia** [comment] 2019-10-17 17:12
I close this one as duplicate of #15 , please reopen and explain if you think it's not the case. Thanks.

**Closed by stellasia** 2019-10-17 17:12 UTC
Labels: duplicate
