### ISSUE TITLE
I wanna show the relationship of the node in neomap,how can I do that

### ISSUE THREAD

**Issue by daciz** [stellasia/neomap#92] opened 2021-05-13 10:02 UTC

**Comment by stellasia** [comment] 2021-05-13 14:06
If you have something like a path, you can use a Polyline rendering, which will basically render a line connecting all consecutive points. You can see an example of how it works here: https://medium.com/neo4j/visualizing-shortest-paths-with-neomap-0-4-0-and-the-neo4j-graph-data-science-plugin-18db92f680de

If your data is more complex, this is not possible right now. but planned to be added when I (or someone else) will have time to work on it (see https://github.com/stellasia/neomap/issues/15)

**Comment by stellasia** [comment] 2021-06-13 14:42
Closing this as it seems to be a duplicate of https://github.com/stellasia/neomap/issues/15, reopen if not.

**Closed by stellasia** 2021-06-13 14:42 UTC
