### ISSUE TITLE
Failure to initialize NeoMap

### ISSUE THREAD

**Issue by acv16** [stellasia/neomap#49] opened 2020-03-10 11:10 UTC
**Describe the bug**
NeoMap does not initialize correctly upon launch from Neo4J Desktop (v. 1.2.4), as can be seen in screenshot. Upon launch it appears unresponsive and blank, and reloading it doesn't have any effect. In rare instances the plugin initialized correctly (showed map), but became similarly unresponsive when update query was clicked on. 

**To Reproduce**
1. Try to open plugin from Neo4J Desktop (v. 1.2.4)
2. If it correctly initializes, try to visualize a query on map.

**Screenshots**
![NeomapIssue](https://user-images.githubusercontent.com/62012352/76306664-9ec5d280-62c7-11ea-9ceb-3886a70eb191.PNG)

**Desktop (please complete the following information):**

 - OS: Windows 10
 - Neo4j *Desktop* Version 1.2.4
 - Neo4j Version 4.0.1
 - Neomap Version: both 0.3.1 and 0.4.0

**Comment by stellasia** [comment] 2020-03-11 18:01
Hi @acv16 ,
Thank you for reporting your issue. I think it is related to #40 and more generally to #19 . I am not able to reproduce the issue for now, so hard to find a solution, but I am pretty sure the way the app connects to Neo4j can be improved, which would solve many issues. I'll try to find a solution but I am unsure I will have time to look deeper at it in the coming days/weeks though :(

**Comment by wagnerjt** [comment] 2020-06-23 02:44
@stellasia -- this may be resolved with #60 for the default 4.0 db. #54 has more details on what we may need to do to support named 4.0 databases

**Comment by stellasia** [comment] 2020-07-04 10:11
@acv16 I'm closing this since it should be fixed with 0.5.0 (release coming in a few minutes). Feel free to reopen if you encounter the same issue again. Thanks.

**Closed by stellasia** 2020-07-04 10:12 UTC
Labels: help wanted, important
